import type { LevelConfig } from './types'

export const CHAOS_LEVEL_ID = 99

/** Daytime Gulf palettes per level mood */
const SKY = {
  clear: { top: '#4a9fd4', bottom: '#87c8e8', fog: '#6eb8c8' },
  hazy: { top: '#6a8faa', bottom: '#b8c4a8', fog: '#9ab0a0' },
  dusty: { top: '#c4844a', bottom: '#e8c090', fog: '#c8a878' },
  smoky: { top: '#8a7060', bottom: '#c8a080', fog: '#a08870' },
  escape: { top: '#5a9fd8', bottom: '#f0c878', fog: '#88b8c8' },
  night: { top: '#0a1628', bottom: '#1a2a44', fog: '#0c1828' },
  chaos: { top: '#1a0a18', bottom: '#3d1838', fog: '#180c16' },
}

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Convoy Launch',
    tag: 'PERSIAN GULF',
    description: 'OP BLACK GOLD — shadow boats, supply rain, first coastal launch.',
    difficulty: 'Easy',
    length: 520,
    speed: 19,
    bombInterval: 3,
    bombBurst: 1,
    obstacleGap: 20,
    mineBias: 0.08,
    patrol: true,
    cargo: false,
    searchlights: false,
    storm: false,
    targetScore: 15000,
    sky: SKY.clear,
  },
  {
    id: 2,
    name: 'Strait Entry',
    tag: 'PATROL CORRIDOR',
    description: 'OP NARROW DOOR — searchlights, paired intercepts, mid-run ambush.',
    difficulty: 'Normal',
    length: 640,
    speed: 20,
    bombInterval: 3.1,
    bombBurst: 1,
    obstacleGap: 19,
    mineBias: 0.1,
    patrol: true,
    cargo: true,
    searchlights: true,
    storm: false,
    targetScore: 25000,
    sky: SKY.hazy,
  },
  {
    id: 3,
    name: 'Mine Belt',
    tag: 'MINE BELT',
    description: 'OP SILENT DEPTH — mine lines, oil slicks, minesweeper surprise.',
    difficulty: 'Hard',
    length: 720,
    speed: 22,
    bombInterval: 3.4,
    bombBurst: 1,
    obstacleGap: 18,
    mineBias: 0.28,
    patrol: true,
    cargo: false,
    searchlights: false,
    storm: false,
    targetScore: 35000,
    sky: SKY.dusty,
  },
  {
    id: 4,
    name: 'Missile Storm',
    tag: 'MISSILE CORRIDOR',
    description: 'OP SKY HAMMER — salvos, EMP gift, double-tap at 50%.',
    difficulty: 'Extreme',
    length: 780,
    speed: 24,
    bombInterval: 2,
    bombBurst: 2,
    obstacleGap: 17,
    mineBias: 0.12,
    patrol: true,
    cargo: true,
    searchlights: true,
    storm: false,
    targetScore: 50000,
    sky: SKY.smoky,
  },
  {
    id: 5,
    name: 'Refinery Run',
    tag: 'OIL TERMINAL',
    description: 'OP FIRELINE — refinery flares, dock traffic, supply lane.',
    difficulty: 'Hard',
    length: 820,
    speed: 25,
    bombInterval: 2.1,
    bombBurst: 2,
    obstacleGap: 16,
    mineBias: 0.18,
    patrol: true,
    cargo: true,
    searchlights: true,
    storm: false,
    targetScore: 55000,
    sky: SKY.smoky,
  },
  {
    id: 6,
    name: 'Radar Silence',
    tag: 'EW CORRIDOR',
    description: 'OP GHOST RADAR — snapshot missiles, radar burst pickup.',
    difficulty: 'Extreme',
    length: 860,
    speed: 26,
    bombInterval: 1.75,
    bombBurst: 2,
    obstacleGap: 15,
    mineBias: 0.18,
    patrol: true,
    cargo: true,
    searchlights: true,
    storm: false,
    targetScore: 62000,
    sky: SKY.hazy,
  },
  {
    id: 7,
    name: 'Twin Convoy',
    tag: 'DUAL TANKERS',
    description: 'OP TWIN SERPENT — dual tankers, crossfire, dual minefield.',
    difficulty: 'Insane',
    length: 900,
    speed: 26,
    bombInterval: 1.55,
    bombBurst: 2,
    obstacleGap: 15,
    mineBias: 0.18,
    patrol: true,
    cargo: true,
    searchlights: true,
    storm: false,
    targetScore: 68000,
    sky: SKY.escape,
  },
  {
    id: 8,
    name: 'Final Tanker Escape',
    tag: 'SAFE WATER',
    description: 'OP LAST BARREL — ambush intercepts, final salvo, safe water.',
    difficulty: 'Insane',
    length: 920,
    speed: 26,
    bombInterval: 2.2,
    bombBurst: 2,
    obstacleGap: 16,
    mineBias: 0.1,
    patrol: true,
    cargo: true,
    searchlights: true,
    storm: false,
    targetScore: 75000,
    sky: SKY.escape,
  },
]

export const CHAOS_LEVEL: LevelConfig = {
  id: CHAOS_LEVEL_ID,
  name: 'Chaos Challenge',
  tag: 'MAX THREAT',
  description: 'OP TOTAL STORM — rotating surprises every segment. Maximum pressure.',
  difficulty: 'Chaos',
  length: 1200,
  speed: 27,
  bombInterval: 1.05,
  bombBurst: 2,
  obstacleGap: 13,
  mineBias: 0.22,
  patrol: true,
  cargo: true,
  searchlights: true,
  storm: false,
  targetScore: 100000,
  sky: SKY.chaos,
}

export function getLevel(id: number): LevelConfig {
  if (id === CHAOS_LEVEL_ID) return CHAOS_LEVEL
  return LEVELS[Math.max(0, Math.min(LEVELS.length - 1, id - 1))]
}

export function isStoryLevel(id: number): boolean {
  return id >= 1 && id <= LEVELS.length
}
